### ISSUE TITLE
digi.xbee.exception.InvalidOperatingModeException: Unsupported operating mode: AT mode

### ISSUE THREAD

**Issue by JBaczuk** [digidotcom/python-xbee#22]
I'm trying to use this on a Macbook using Python3.  I have verified that the AP parameter is set to API Enabled [1] in XCTU.  When I try to run the following code:

```
from digi.xbee.devices import XBeeDevice

device = XBeeDevice('/dev/tty.usbserial-AL02DVXW', 115200)

device.open()

while True:
    xbee_message = device.read_data()
    
    print(xbee_message)
```

I get `digi.xbee.exception.InvalidOperatingModeException: Unsupported operating mode: AT mode` even though it is in API enabled [1].  Any help is appreciated.

**Comment by JBaczuk** [comment]
I think it may be because both devices must be in API mode, unfortunately I don't have access to the code on the second device, and when I put it in API mode, it appears to break the code and no longer transmits.

**Comment by yxmagithub** [comment]
Jordan, do you solve this invalidOperatingModeException issue? if so How ?

**Comment by JBaczuk** [comment]
@yxmagithub IIRC, I was not able to use this library for what I was trying to do. I think it only supports API mode, and I needed AT mode.
