### ISSUE TITLE
won't work with python2.7

### ISSUE THREAD

**Issue by venkyfun** [digidotcom/python-xbee#26]
Hello,
This library is not working with python2.7
is this library meant for only python3,is there any other library for 2.7

**Comment by venkyfun** [comment]
i want to discover the nodes using this library in python2.7
can i have the sample code

**Comment by rubenmoral** [comment]
Hi @venkyfun,

The library is only compatible with Python 3. We don't currently have a version for 2.7.

Best regards.

**Comment by venkyfun** [comment]
thankyou @rubenmoral

**Comment by venkyfun** [comment]
Hi Ruben

Venky here.

I just wanna ask you one thing.

Is there any possibility of getting this library in Python2.7


Venkatesh.M

**Comment by rubenmoral** [comment]
Hi @venkyfun,

I'm afraid that there is not in the near future. We will let you know if the plan changes.

Best regards.
