### ISSUE TITLE
Regarding setting parameters on a remote Xbee from a local Xbee

### ISSUE THREAD

**Issue by verossi** [digidotcom/python-xbee#40]
Hi,
I am using 2 series 1 XBee pro modules. One is on the explorer board from sparkfun ,which is my local Xbee module. Both these are connected to my computer comports. The firmware version is 10ec and both are configured as 802.15.4 devices. 
Now I am using the python API to set parameters in the remote XBee from my local XBee device. I follow the SetAndGetParametersSample.py. This is what I try to do.

 REMOTE_NODE_ID="REMOTE"
 device = XBeeDevice(PORT, BAUD_RATE)       #Local Xbee
   try:
        device.open()
        print(device)
        xbee_network = device.get_network()
        remote_device = xbee_network.discover_device(REMOTE_NODE_ID)
        # Set parameters.
        remote_device.set_parameter("DH",utils.hex_string_to_bytes("XXXXXX"))
        remote_device.set_parameter("DL",utils.hex_string_to_bytes("xxxxxxxx"))

I get a timeout exception error.
I use python 3.6 . I would like to know if this is even possible to do it this way? I am a beginner in this area, so any help would be useful. If this is not the way then could anyone tell me how the remote parameters can be set from a local device?

Related Errors: 
SetAndGetParametersSample/parameter.py", line 58, in main
    remote_device.set_parameter("DH",utils.hex_string_to_bytes("xxxxxx"))

\digi\xbee\devices.py", line 4805, in set_parameter
           response = self._local_xbee_device.send_packet_sync_and_get_response(packet_to_send)
          
 digi\xbee\devices.py", line 2423, in send_packet_sync_and_get_response
           raise TimeoutException("Response not received in the configured timeout.")
           digi.xbee.exception.TimeoutException

**Comment by diescalo** [comment]
Seems to be the same communication problem described in https://github.com/digidotcom/python-xbee/issues/41 Please verify both modules can see and communicate each other (using XCTU for example) If you are still getting the timeout error create another issue.

Thanks!
