### ISSUE TITLE
API Frame 0x09 (Queued AT command) is not implemented

### ISSUE THREAD

**Issue by mlasevich** [digidotcom/python-xbee#52]
I am seeing `device.enable_apply_changes(False)` not being respected  on local Zigbee Devices, and upon looking at the code, it sure looks like the API frame required for that (0x09 - Queued AT command) is not even implemented.

**Comment by rubenmoral** [comment]
Hi @mlasevich,

Thanks for reporting this issue. We have fixed it (see commit 9ca9380f5670945e0a3824da94b65439b276d292) and will be included in the next release. In the meantime, you can download the source code from the `master` branch and install the library from there (see instructions at https://github.com/digidotcom/python-xbee/blob/master/README.rst#install-from-source).

Sorry for the inconvenience.

Best regards.
