### ISSUE TITLE
Disable printing serial bytes to console

### ISSUE THREAD

**Issue by aidanh010** [digidotcom/python-xbee#61]
The library prints every serial message like so:

```
/dev/ttyUSB0RECEIVED    OperatingMode.API_MODE7E 00 05 88 09 4E 49 00 D7                        
DEBUG:digi.xbee.reader:/dev/ttyUSB0RECEIVED    OperatingMode.API_MODE7E 00 05 88 09 4E 49 00 D7
```

This interferes with the program interface and it appears to cause high CPU usage when a lot of packets are being transmitted. Is there a way to disable this output?

**Comment by rubenmoral** [comment]
Hi @aidanh010,

Yes, there is. The library uses the Python's `logging` module, you can disable it by calling the following method in your application:

```
import logging

[...]

logging.disable()
```

Best regards.
