### ISSUE TITLE
Is python xbee librarte supported on raspian?

### ISSUE THREAD

**Issue by danieljoserm** [digidotcom/python-xbee#75]

**Comment by rubenmoral** [comment]
Hi @danieljoserm. Yes, it is, as long as you have Python 3 installed on it.

**Comment by aang7** [comment]
Hello, I'm just trying to connect to my XBee module with a raspberry pi 3 and I can't. Some one knows how to achieve this?
I've already have installed the library and using python 3.7.3 within raspbian buster and nothing...
