### ISSUE TITLE
NoneType attribute error 

### ISSUE THREAD

**Issue by jimvdH** [digidotcom/python-xbee#9]
Hello , 
I bought these new Xbee 868 and tried to use them in API mode with this python library, but whatever I try I keep getting this error and i have no clue what i did wrong. I just used the example network/DiscoverDevicesSample and followed the exact instructions. Could somebody please help me?

+---------------------------------------------+
 | XBee Python Library Discover Devices Sample |
 +---------------------------------------------+

The thread 'MainThread' (0x1c64) has exited with code 0 (0x0).
Traceback (most recent call last):
  File "C:\Users\Jim\source\repos\start\start\start.py", line 70, in <module>
    main()
  File "C:\Users\Jim\source\repos\start\start\start.py", line 34, in main
    device.open()
  File "C:\Users\Jim\AppData\Local\Programs\Python\Python36-32\lib\site-packages\digi\xbee\devices.py", line 1290, in open
    self.read_device_info()
  File "C:\Users\Jim\AppData\Local\Programs\Python\Python36-32\lib\site-packages\digi\xbee\devices.py", line 315, in read_device_info
    self._protocol = XBeeProtocol.determine_protocol(self._hardware_version.code, self._firmware_version)
AttributeError: 'NoneType' object has no attribute 'code'
The program '[6768] python.exe' has exited with code -1073741510 (0xc000013a).

**Comment by rubenmoral** [comment]
Hi @jimvdH,

The support for XBee SX 868 modules was added after the release of version 1.0.0 (see commit 09ade1e2dcdd18dab0b74ee5d92c4c65762a6270), so it will be included in the next release.

In the meantime, you can download the source code from the `master` branch and install the library from there (see instructions at https://github.com/digidotcom/python-xbee/blob/master/README.rst#install-from-source).

Sorry for the inconvenience.

Best regards.
